### PR TITLE
Add badges; Add action to test on push; Use pytest; Add coverage report

### PR DESCRIPTION
**Pull request by delijati**
Add badges; Add action to test on push; Use pytest; Add coverage report

### CODE REVIEW

**Comment by KiraPC** [comment]
@delijati 

Thanks for your PR.

Just to understand, why did you add a new tests? There are two sample apps that are also used as test cases.

Also the GitHub Action is configured, but triggered just in PR, even if I have to configure it in the settings, because someone last week tried to run an Action to mine Crypto on GitHub servers.

**Comment by delijati** [comment]
Yeah i just saw your defined actions too late, then i already had added mine :D It would also be nice to have the test run on every push and locally via `pytest tests`. The project currently look like there are no tests at all (no `tests` folder no badge).

The problem with the crypto miner should be Github's problem and not ours ;)

**Comment by KiraPC** [comment]
@delijati 

Ok, perfect. Tomorrow I'll adjust your work, merging with what I already did, like action and tests, putting them from example to tests folder, then merge the PR.

Anyway, I disabled action because I don't want to make them life easy 😁

**Comment by delijati** [comment]
awesome

**Pull request merged**
